### ISSUE TITLE
feedback skip's

### ISSUE THREAD

**Issue by TimeForANinja** [source-engine-discord/BotHATTwaffle2#21]
3/5 of my feedback's were skipped on todays de_quarry playtest
they still appeared in the .txt

**Comment by tophattwaffle** [comment]
Skipped in what way? The in game reply to to your feedback message?

**Comment by TimeForANinja** [comment]
did get that - missed out on the website
no idea if i'm even right here

**Comment by tophattwaffle** [comment]
So your feedback was in the txt file, but not in the website?

**Comment by TimeForANinja** [comment]
yep

**Comment by tophattwaffle** [comment]
Looks like an issue with the demo parser - which runs behind the scenes. I'll contact the one that maintains that code to get it resolved.
